// Code generated by "stringer -type Token"; DO NOT EDIT.

package scanner

import "strconv"

const _Token_name = "LparenRparenSymbolNumberStringEOF"

var _Token_index = [...]uint8{0, 6, 12, 18, 24, 30, 33}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
